IT'S A TRAP!
Finally fixes the traps so that they (seem to) work 100% as expected.

If you ran the script then hit 'n' to create an account, you could hit
^C to return to the main menu. BUT if you then hit 'n' again, followed
by another ^C, the SIGINT would be ignored and would be echoed to shell.

This commit makes it so the main menu is ran in a subshell so that we
can trap SIGINT in the child process instead and simply exit when ^C is
pressed from any page other than the main menu. If it IS the main menu,
we instead spit out a special exit code so that we can check that and
break out of the loop if it's a match when the subshell is exited.

Now you can go to the creation menu and hit ^C to return to the main
menu as many times as you want and it'll keep working. Success!

Source of inspiration: https://unix.stackexchange.com/a/67552/42182
(kill 0 isn't used here because it spits out "Terminated <PID>")

diff --git a/muttconf b/muttconf
--- a/muttconf
+++ b/muttconf
@@ -19,12 +19,20 @@
 
 set -Eeo pipefail
 
-trap '[ $? == 69 ] && main || error -e "\nAborted due to error" && exit 1' ERR
-trap '[ "$page" == "Main Menu" ] && info -e "\nGoodbye!" && exit 0 || return 69' SIGINT
+# If exit status is 69, user hit ^C from main menu so we'll ignore it
+trap '[ $? != 69 ] && error -e "\nAborted due to error" && exit 1' ERR
 
 readonly _VERSION="0.0.0"
 
 main() {
+    while :; do
+        ( trap '[ "$page" == "Main Menu" ] && quit || exit 0' SIGINT
+            main_menu
+        ); [ $? -eq 69 ] && break
+    done
+}
+
+main_menu() {
     page="Main Menu"
     print_logo
 
@@ -32,10 +40,8 @@ main() {
         n)
             create_account ;;
         q)
-            info "Goodbye!" && exit 0 ;;
+            quit ;;
     esac
-
-    main
 }
 
 create_account() {
@@ -74,7 +80,7 @@ list_actions() {
     local actions=() validopts=() opt
 
     case "${FUNCNAME[1]}" in
-        main)
+        main_menu)
             actions+=("n;Create a new account;success")
             actions+=("q;Quit;error")
             ;;
@@ -113,6 +119,11 @@ print_logo() {
 
     warn -en "\n    $(printf "%-55s" "[ ${page} ]")"
     success -e "     Version ${_VERSION}\n"
+}
+
+quit() {
+    info -e "\nGoodbye!"
+    exit 69
 }
 
 info() {
